{% set version = "1.61.0" %}

package:
  name: boost-gorgon
  version: {{ version }}

source:
  path:  {{ RECIPE_DIR }}/../src

build:
  number: 0

requirements:

test:
  commands:
    # Verify dynamic libraries.
    {% set win_vstr = "_".join(version.split(".")[:2]) %}
    {% set boost_libs = [
            "python",
            "serialization"
    ] %}
    {% for each_boost_lib in boost_libs %}
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.lib exit 1  # [win]
    {% endfor %}

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - shadowwalkersb
